### ISSUE TITLE
Testing performance

### ISSUE THREAD

**Issue by davidheijkamp** [naturalis/role_treebase#11]
With the script on https://github.com/TreeBASE/supertreebase the performance of the TreeBASE server can be tested. It's also handy for generating a cache for all records.

**Comment by davidheijkamp** [comment]
@fpieters Can you have a look at testing the performance with this script?

**Comment by fpieters** [comment]
It works, but there seems to be some nexml files that are too big. They spawn tomcat zombie processes. Apparently this is a known bug.

**Comment by rvosa** [comment]
Yes, it is. Workaround:
https://github.com/TreeBASE/supertreebase/commit/d26079d4cbea5495705b047a3f362a74e662ef7b

**Comment by fpieters** [comment]
Then it works nicely. Also the caching works and stays for 1 month.
